[tool.black]
line-length = 94

[tool.pytest.ini_options]
minversion = "8.0"
addopts = "-ra -q"
testpaths = [
    "tests"
]
markers = [
    "asyncio: mark test as asyncio to run async code"
]

[tool.flake8]
max-line-length = 94
ignore = ["E203", "W503"]
exclude = [".git", "__pycache__", "env", "venv", "build", "dist", "*.egg-info"]

